### ISSUE TITLE
markdown or bbcode support

### ISSUE THREAD

**Issue by lostfile1** [fgahr/termchan#6] opened 2021-01-02 14:39 UTC
i don't think doing things like embedding image or videos would be a good idea but maybe the ability to create bold text or quote someone or list or a strike-through or even colorize it

**Comment by fgahr** [comment] 2021-01-02 17:12
Users are free to put ANSI codes in their messages.

No cleaning of messages is performed so when viewed through a terminal everything is shown as intended.
Making that process easier (quite cumbersome in most editors) is up to the user or a smart client application.
termchan-cli will add no support for this as it is intended as a minimal solution showcasing general interactions. People can configure vim (or whatever other editor they use) to make it simpler.

As for quoting, I have thought about this a bit. Treating, say, `@123` specially and insert a link to that post could be done in HTML output but for ANSI or JSON modes I see no clear way to add it (other than coloring in ANSI). It's more something a potential client application would have to support. JSON output was added with more advanced clients in mind.
If you have a clear vision of what quote support should look like, let me know.

So far, no parsing or other manipulation (other than whitespace trimming) is performed in post contents and I'd like to keep it that way if at all possible.

**Comment by lostfile1** [comment] 2021-01-02 17:43
oh cool

**Comment by lostfile1** [comment] 2021-01-03 04:39
i have an instance on paperchan.ddns.net:8088 use the port

**Comment by fgahr** [comment] 2021-01-03 15:05
Can I close this issue?

**Closed** 2021-01-03 15:54 UTC
